# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SyncAndTranscodeMusicFiles < Formula
  desc "Syncs and transcodes music files to MP3 for playback on car audio systems"
  homepage "https://github.com/topfunky/learning-sync-and-transcode-music-files"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/topfunky/learning-sync-and-transcode-music-files/releases/download/v0.0.2/sync-and-transcode-music-files_0.0.2_darwin_amd64.tar.gz"
      sha256 "dcba99c561bd77742fbeaac2da0209ffe8e8d70c727f1276ba0f93e99a8fa825"

      define_method(:install) do
        bin.install "sync-and-transcode-music-files"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/topfunky/learning-sync-and-transcode-music-files/releases/download/v0.0.2/sync-and-transcode-music-files_0.0.2_darwin_arm64.tar.gz"
      sha256 "b95538b3a5b598587664900fe728ad9128907df5f5b6684f69f2de7f24dd4069"

      define_method(:install) do
        bin.install "sync-and-transcode-music-files"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/topfunky/learning-sync-and-transcode-music-files/releases/download/v0.0.2/sync-and-transcode-music-files_0.0.2_linux_amd64.tar.gz"
      sha256 "82b4bd3f5b6456ac4b53e7130fc5d565490fa2fbc83fd1c343df1275e3240981"
      define_method(:install) do
        bin.install "sync-and-transcode-music-files"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/topfunky/learning-sync-and-transcode-music-files/releases/download/v0.0.2/sync-and-transcode-music-files_0.0.2_linux_arm64.tar.gz"
      sha256 "77d3851a8342dc61360356199e38c715b246b86bf3349c0309d5d8a0577ab3e2"
      define_method(:install) do
        bin.install "sync-and-transcode-music-files"
      end
    end
  end
end
