# This file was generated by GoReleaser. DO NOT EDIT.
cask "countdown" do
  name "countdown"
  desc "CLI countdown timer with spinner animation"
  homepage "https://github.com/topfunky/countdown"
  version "0.0.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "countdown"

  on_macos do
    on_intel do
      url "https://github.com/topfunky/countdown/releases/download/v#{version}/countdown_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/topfunky/countdown"
      sha256 "98a86f5e7c9feddacffc1fbdc9704c4bb30ba891aa05817f15b5aa250e5abc76"
    end
    on_arm do
      url "https://github.com/topfunky/countdown/releases/download/v#{version}/countdown_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/topfunky/countdown"
      sha256 "6fc270b157504d0058f2ca8494f0af7d3a80044b21103d37e54c8eceeb48bba0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/topfunky/countdown/releases/download/v#{version}/countdown_#{version}_linux_amd64.tar.gz",
        verified: "github.com/topfunky/countdown"
      sha256 "bc5e561b3a32115a5dd9fa3870a6f0df226941a60fcfe0adb41c20823aa435d2"
    end
    on_arm do
      url "https://github.com/topfunky/countdown/releases/download/v#{version}/countdown_#{version}_linux_arm64.tar.gz",
        verified: "github.com/topfunky/countdown"
      sha256 "3e9f18dbf5b4812802280c1bca782b14455fa37f96ade0bb4c5dbaad604a52cc"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/countdown"]
    end
  end

  # No zap stanza required
end
