# This file was generated by GoReleaser. DO NOT EDIT.
cask "countdown" do
  name "countdown"
  desc "CLI countdown timer with spinner animation"
  homepage "https://github.com/topfunky/countdown"
  version "0.0.10"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "countdown"

  on_macos do
    on_intel do
      url "https://github.com/topfunky/countdown/releases/download/v#{version}/countdown_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/topfunky/countdown"
      sha256 "3dd2be32e668f5d7e67d3d338aa7ec29e47e3d2930b7364e08176b133e73882b"
    end
    on_arm do
      url "https://github.com/topfunky/countdown/releases/download/v#{version}/countdown_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/topfunky/countdown"
      sha256 "be1fe7438161980edde28852b7762725717f849e2e49119fd535b40ccd62cf6c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/topfunky/countdown/releases/download/v#{version}/countdown_#{version}_linux_amd64.tar.gz",
        verified: "github.com/topfunky/countdown"
      sha256 "63f87abb7505e8aa300676da7f09043acb026efc9d24747d56e51a3e0d688b46"
    end
    on_arm do
      url "https://github.com/topfunky/countdown/releases/download/v#{version}/countdown_#{version}_linux_arm64.tar.gz",
        verified: "github.com/topfunky/countdown"
      sha256 "c22ced801a17b9fdd568f3156ff50cf908ccd766d404b016ae223a795c9dba7a"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/countdown"]
    end
  end

  # No zap stanza required
end
