# This file was generated by GoReleaser. DO NOT EDIT.
cask "og-image-generator" do
  name "og-image-generator"
  desc "Generate Open Graph images from the command line"
  homepage "https://github.com/topfunky/og-image-generator-go"
  version "0.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "og-image-generator"

  on_macos do
    on_intel do
      url "https://github.com/topfunky/og-image-generator-go/releases/download/v#{version}/og-image-generator_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/topfunky/og-image-generator-go"
      sha256 "ab3f38ccfc76919fa358e3cd34cdc4c684a2090a02544df86636b069b55dc107"
    end
    on_arm do
      url "https://github.com/topfunky/og-image-generator-go/releases/download/v#{version}/og-image-generator_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/topfunky/og-image-generator-go"
      sha256 "21db02f9c7822d3d6f6a92ef42e9178905833771d25a077a44979678694e50c9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/topfunky/og-image-generator-go/releases/download/v#{version}/og-image-generator_#{version}_linux_amd64.tar.gz",
        verified: "github.com/topfunky/og-image-generator-go"
      sha256 "7769e8e34bb7284d3b32a9c304366543fcc579cabfd431a2c3bf484bbefeab9f"
    end
    on_arm do
      url "https://github.com/topfunky/og-image-generator-go/releases/download/v#{version}/og-image-generator_#{version}_linux_arm64.tar.gz",
        verified: "github.com/topfunky/og-image-generator-go"
      sha256 "996427b3f8cceb37c4f6ad355e5393bad22eaada122d96370f205815e658dfd2"
    end
  end

  # No zap stanza required
end
