# This file was generated by GoReleaser. DO NOT EDIT.
cask "og-image-generator" do
  name "og-image-generator"
  desc "Generate Open Graph images from the command line"
  homepage "https://github.com/topfunky/og-image-generator-go"
  version "0.0.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "og-image-generator"

  on_macos do
    on_intel do
      url "https://github.com/topfunky/og-image-generator-go/releases/download/v#{version}/og-image-generator_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/topfunky/og-image-generator-go"
      sha256 "e02d3412310155d26e8437724988c04bbfbcd1c2c3e19a39301db6bd18ba1c82"
    end
    on_arm do
      url "https://github.com/topfunky/og-image-generator-go/releases/download/v#{version}/og-image-generator_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/topfunky/og-image-generator-go"
      sha256 "15b9f8bffdba5781173332e6a697f81bac14817674b915d211784c6155dc7598"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/topfunky/og-image-generator-go/releases/download/v#{version}/og-image-generator_#{version}_linux_amd64.tar.gz",
        verified: "github.com/topfunky/og-image-generator-go"
      sha256 "33cf1183db74914a228a43b9e3636bc77e2f0ed84ed20f5e746a37a1a483ff6c"
    end
    on_arm do
      url "https://github.com/topfunky/og-image-generator-go/releases/download/v#{version}/og-image-generator_#{version}_linux_arm64.tar.gz",
        verified: "github.com/topfunky/og-image-generator-go"
      sha256 "fb6e1957250f7dd84897b8f1576761837b11ab54751e28cd222eaff0962b280e"
    end
  end

  # No zap stanza required
end
