# This file was generated by GoReleaser. DO NOT EDIT.
cask "og-image-generator" do
  name "og-image-generator"
  desc "Generate Open Graph images from the command line"
  homepage "https://github.com/topfunky/og-image-generator-go"
  version "0.0.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "og-image-generator"

  on_macos do
    on_intel do
      url "https://github.com/topfunky/og-image-generator-go/releases/download/v#{version}/og-image-generator_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/topfunky/og-image-generator-go"
      sha256 "50d8d0c18fb6e4ed4de968885c5db8b2c052bdea2d837ae0a99a5474a42677b3"
    end
    on_arm do
      url "https://github.com/topfunky/og-image-generator-go/releases/download/v#{version}/og-image-generator_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/topfunky/og-image-generator-go"
      sha256 "d34495f33691a6c8693780a384ef857393f4f31778c1bb89c358f6a910872af8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/topfunky/og-image-generator-go/releases/download/v#{version}/og-image-generator_#{version}_linux_amd64.tar.gz",
        verified: "github.com/topfunky/og-image-generator-go"
      sha256 "28f400becf770477b24ffafca31c6a340624c538f8b2d171f1dff8136d343ff7"
    end
    on_arm do
      url "https://github.com/topfunky/og-image-generator-go/releases/download/v#{version}/og-image-generator_#{version}_linux_arm64.tar.gz",
        verified: "github.com/topfunky/og-image-generator-go"
      sha256 "b5a601f1b353abc58d67562b9a84fd96bed7b6cfc3dd3dc56753b4ef450ef5d4"
    end
  end

  # No zap stanza required
end
