# This file was generated by GoReleaser. DO NOT EDIT.
cask "tiny-timer" do
  name "tiny-timer"
  desc "A simple command-line Pomodoro timer with an animated progress bar"
  homepage "https://github.com/topfunky/tiny-timer"
  version "0.0.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tiny-timer"

  on_macos do
    on_intel do
      url "https://github.com/topfunky/tiny-timer/releases/download/v#{version}/tiny-timer_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/topfunky/tiny-timer"
      sha256 "a242ef575e7f7b0c40fd13ac86b13cd390ee9f376b7eb9bdd58256fe5da64ded"
    end
    on_arm do
      url "https://github.com/topfunky/tiny-timer/releases/download/v#{version}/tiny-timer_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/topfunky/tiny-timer"
      sha256 "3350283c6a4e54e872e916153e13d3069b4aed2a481a2432bb9f8c5ec84cab84"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/topfunky/tiny-timer/releases/download/v#{version}/tiny-timer_#{version}_linux_amd64.tar.gz",
        verified: "github.com/topfunky/tiny-timer"
      sha256 "e5570394ae607ccf51205deaa840886b19e078608206f0ee0b3a9643f70b36fa"
    end
    on_arm do
      url "https://github.com/topfunky/tiny-timer/releases/download/v#{version}/tiny-timer_#{version}_linux_arm64.tar.gz",
        verified: "github.com/topfunky/tiny-timer"
      sha256 "f9ec9401e575f5fc0a98a819e26161ff3d69ee0480b255d4d300475aee55f787"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tiny-timer"]
    end
  end

  # No zap stanza required
end
