# This file was generated by GoReleaser. DO NOT EDIT.
cask "tiny-timer" do
  name "tiny-timer"
  desc "A simple command-line Pomodoro timer with an animated progress bar"
  homepage "https://github.com/topfunky/tiny-timer"
  version "0.0.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tiny-timer"

  on_macos do
    on_intel do
      url "https://github.com/topfunky/tiny-timer/releases/download/v#{version}/tiny-timer_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/topfunky/tiny-timer"
      sha256 "bc94cee467c270b170634981c13d96d31d1320f06aeac45e6ad229c0c72c1b2b"
    end
    on_arm do
      url "https://github.com/topfunky/tiny-timer/releases/download/v#{version}/tiny-timer_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/topfunky/tiny-timer"
      sha256 "e1e471c7efac91f2050ff4bb0690888922fe303813b79dda69fe052c0bf9e980"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/topfunky/tiny-timer/releases/download/v#{version}/tiny-timer_#{version}_linux_amd64.tar.gz",
        verified: "github.com/topfunky/tiny-timer"
      sha256 "0ad3f531a0d229db1e91da65c8f3fdd2065b6c7332dae1158af2c3b8f3496464"
    end
    on_arm do
      url "https://github.com/topfunky/tiny-timer/releases/download/v#{version}/tiny-timer_#{version}_linux_arm64.tar.gz",
        verified: "github.com/topfunky/tiny-timer"
      sha256 "e0f0fb54938eb0c8e10cf9dc7acffe288ad0a5caeee8c095d26238063819cfed"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tiny-timer"]
    end
  end

  # No zap stanza required
end
