# This file was generated by GoReleaser. DO NOT EDIT.
cask "tiny-timer" do
  name "tiny-timer"
  desc "A simple command-line Pomodoro timer with an animated progress bar"
  homepage "https://github.com/topfunky/tiny-timer"
  version "0.0.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tiny-timer"

  on_macos do
    on_intel do
      url "https://github.com/topfunky/tiny-timer/releases/download/v#{version}/tiny-timer_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/topfunky/tiny-timer"
      sha256 "3ab439506232340b39f54ced170fe1588a2326d864c3d21cccea3f778ada7f44"
    end
    on_arm do
      url "https://github.com/topfunky/tiny-timer/releases/download/v#{version}/tiny-timer_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/topfunky/tiny-timer"
      sha256 "456a1928bd919823b242ca3adaa5a47eae0d43150bb24bfc52249875d3a53e2d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/topfunky/tiny-timer/releases/download/v#{version}/tiny-timer_#{version}_linux_amd64.tar.gz",
        verified: "github.com/topfunky/tiny-timer"
      sha256 "4d2735293afca64994465a5dd517cfb082203813f2ba3eb450aaa2a2ffe8beac"
    end
    on_arm do
      url "https://github.com/topfunky/tiny-timer/releases/download/v#{version}/tiny-timer_#{version}_linux_arm64.tar.gz",
        verified: "github.com/topfunky/tiny-timer"
      sha256 "e071f73d3b1c00ac8d3c4cc56cb1cecebbb7bb705285805e43b39ff7cf8115a9"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tiny-timer"]
    end
  end

  # No zap stanza required
end
