# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Countdown < Formula
  desc "CLI countdown timer with spinner animation"
  homepage "https://github.com/topfunky/countdown"
  version "0.0.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/topfunky/countdown/releases/download/v0.0.7/countdown_0.0.7_darwin_amd64.tar.gz"
      sha256 "ff5716af6fa86ff7decddeaa3905dd3411238c4fef52ce5cb88f799776fc9d4a"

      def install
        bin.install "countdown"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/topfunky/countdown/releases/download/v0.0.7/countdown_0.0.7_darwin_arm64.tar.gz"
      sha256 "d7f7b454e083894edbd4dbf2641b8c0ed7630e9eed238058a08f1cc73ac60757"

      def install
        bin.install "countdown"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/topfunky/countdown/releases/download/v0.0.7/countdown_0.0.7_linux_amd64.tar.gz"
      sha256 "dce28dcf7ee36cb87233eb7fa1c018fc91a34edb1ac79f6089445ec646fed6c1"
      def install
        bin.install "countdown"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/topfunky/countdown/releases/download/v0.0.7/countdown_0.0.7_linux_arm64.tar.gz"
      sha256 "c3d9d07f2b2107067b2f96e2a74268fb6f19f98a55e4dde873d0f6a2910014f8"
      def install
        bin.install "countdown"
      end
    end
  end

  test do
    system "#{bin}/countdown", "--version"
  end
end
